# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
sudo: required
warnings_are_errors: true

r:
  - release
  - devel
  
apt_packages:
  - libopenbabel-dev
  
r_github_packages:
  - jasenfinch/mzAnnotation
  - jasenfinch/MFassign
  
notifications:
    email:
    on_success: change
    on_failure: change